# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-21 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='NA')),
                ('admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('payment_id', models.CharField(max_length=30, null=True, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('transfer_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from', to='main.UserProfile')),
                ('transfer_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to', to='main.UserProfile')),
            ],
        ),
    ]
