# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-21 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
