# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('response', models.TextField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
