# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_botcommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcommand',
            name='command_response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
