# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_botcommand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botcommand',
            options={'verbose_name': 'Bot Command', 'verbose_name_plural': 'Bot Commands'},
        ),
    ]
