# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190301_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_da',
            field=models.BooleanField(default=False),
        ),
    ]
