# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190301_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcommand',
            name='command_name',
            field=models.CharField(choices=[('!food', 'FOOD_DROP_AREAS'), ('!safe', 'SAFE_LOCATIONS'), ('!contact', 'EMERGENCY_CONTACTS')], max_length=10, unique=True),
        ),
    ]
