# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userprofile_is_da'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_food_req',
            field=models.BooleanField(default=True),
        ),
    ]
