# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-02 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_uploadfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'verbose_name': 'Uploaded File', 'verbose_name_plural': 'Uploaded Files'},
        ),
    ]
