# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-02 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190302_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_food_req',
            field=models.BooleanField(default=False),
        ),
    ]
