# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-02 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190302_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='filer',
            field=models.FileField(upload_to='media/'),
        ),
    ]
